---
title: "Life Expectancies for selected populations"
author: "Jon Minton"
date: '2022-07-23'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Aim

This appendix will show the life expectancies for the populations compared in the paper. 


# Data 

```{r}
library(tidyverse)

# load data 
hmd_lt <- read_rds("https://github.com/JonMinton/change-in-ex/blob/main/data/lifetables.rds?raw=true")


# Labels for codes 
country_code_lookup <- 
  tribble(
    ~code, ~country,
    "DEUTNP", "Germany",
    "DEUTE", "East Germany",
    "DEUTW", "West Germany",
    "ESP", "Spain",
    "FRATNP", "France", 
    "ITA", "Italy",
    "GBRTENW", "England & Wales",
    "GBR_SCO", "Scotland",
    "DEUTSYNTH", "Synthetic Germany",
    "NLD", "Netherlands"
  )

countries_of_interest <- c(
  "GBRTENW",
  "GBR_SCO",
  "GBR_UK",
  "FRATNP",
  "ESP",
  "ITA",
  "DEUTNP",
  "DEUTE", 
  "DEUTW",
  "NLD"
)

source("https://raw.githubusercontent.com/JonMinton/change-in-ex/main/R/make_synthetic_germany_functions.R")

source("https://raw.githubusercontent.com/JonMinton/change-in-ex/main/R/make_pop_selection.R")

```

# Graphs 

## Life Expectancy at birth

```{r}
hmd_ex_selected_countries_with_synth %>% 
  left_join(country_code_lookup) %>% 
  mutate(country = factor(country, levels = c("England & Wales", "Scotland", "Synthetic Germany", "Spain", "France", "Italy", "Netherlands"))) %>% 
  filter(!is.na(country)) %>% 
  filter(between(year, 1980, 2020)) %>% 
  filter(x == 0) %>% 
  ggplot(aes(x = year, y = ex, group = sex, colour = sex, linetype = sex)) + 
  geom_line() +
  facet_wrap(~country) +
  labs(
    x = "Year",
    y = "Life Expectancy at birth",
    title = "Life expectancies at birth for selected nations",
    subtitle = "1980 to 2020 or latest available year",
    caption = "Source: Human Mortality Database"
  )
```
Equivalently

```{r}
hmd_ex_selected_countries_with_synth %>% 
  left_join(country_code_lookup) %>% 
  mutate(country = factor(country, levels = c("England & Wales", "Scotland", "Synthetic Germany", "Spain", "France", "Italy", "Netherlands"))) %>% 
  filter(!is.na(country)) %>% 
  filter(between(year, 1980, 2020)) %>% 
  filter(x == 0) %>% 
  ggplot(aes(x = year, y = ex, group = country, colour = country, linetype = country)) + 
  geom_line() +
  facet_wrap(~sex) +
  labs(
    x = "Year",
    y = "Life Expectancy at birth",
    title = "Life expectancies at birth for selected nations",
    subtitle = "1980 to 2020 or latest available year",
    caption = "Source: Human Mortality Database"
  )

```

## Life expectancy at age 65 


```{r}
hmd_ex_selected_countries_with_synth %>% 
  left_join(country_code_lookup) %>% 
  mutate(country = factor(country, levels = c("England & Wales", "Scotland", "Synthetic Germany", "Spain", "France", "Italy", "Netherlands"))) %>% 
  filter(!is.na(country)) %>% 
  filter(between(year, 1980, 2020)) %>% 
  filter(x == 65) %>% 
  ggplot(aes(x = year, y = ex, group = sex, colour = sex, linetype = sex)) + 
  geom_line() +
  facet_wrap(~country) +
  labs(
    x = "Year",
    y = "Life Expectancy at age 65",
    title = "Life expectancies at age 65 years  for selected nations",
    subtitle = "1980 to 2020 or latest available year",
    caption = "Source: Human Mortality Database"
  )
```
Equivalently: 

```{r}
hmd_ex_selected_countries_with_synth %>% 
  left_join(country_code_lookup) %>% 
  mutate(country = factor(country, levels = c("England & Wales", "Scotland", "Synthetic Germany", "Spain", "France", "Italy", "Netherlands"))) %>% 
  filter(!is.na(country)) %>% 
  filter(between(year, 1980, 2020)) %>% 
  filter(x == 65) %>% 
  ggplot(aes(x = year, y = ex, group = country, colour = country, linetype = country)) + 
  geom_line() +
  facet_wrap(~sex) +
  labs(
    x = "Year",
    y = "Life Expectancy at age 65",
    title = "Life expectancies at age 65 years  for selected nations",
    subtitle = "1980 to 2020 or latest available year",
    caption = "Source: Human Mortality Database"
  )
```

